version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: CustomFormApp.Server/Dockerfile
    ports:
      - "8000:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    volumes:
      - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys
      - ./path-to-your-certificate:/https/aspnetapp.pfx
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ./CustomFormApp.Server/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - server

  frontend:
    build:
      context: ./customformapp.client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: customformdb_user
      POSTGRES_PASSWORD: NbFHTM0HJqa8wZ9WBPV9KBFuPpeEtYp7
      POSTGRES_DB: customformdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
